name: 'Remove unlabled images in ECR'
description: 'Remove unlabled images in ECR'
inputs:
    repository:
        description: 'repository name'
        required: true
    access_key:
        description: 'access key aws'
        required: true
    secret_key:
        description: 'secret key aws'
        required: true
runs:
    using: 'node16'
    main: 'dist/index.js'
