on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        name: test
        steps:
            -
                name: remove images unlabelled
                id: rm-images-ecr
                uses: dcorrea777/action-rm-unlabeled-images-ecr@v1.2
                with:
                    repository: 'dcorrea'
                    access_key: ${{ secrets.ACCESS_KEY }}
                    secret_key: ${{ secrets.SECRET_KEY }}
